### ISSUE TITLE
registry

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/timefuzz#2]
this package is listed in the registry but has no docs.ropensci.org website?

**Comment by sckott** [comment]
maybe b/c it always fails https://dev.ropensci.org/job/timefuzz/7/console

**Comment by sckott** [comment]
ooof, now getting 403 errors on dev.ropensci.org, asking jeroen

**Comment by sckott** [comment]
fixed

**Comment by maelle** [comment]
Yay!
